spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/sns
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false  # 실무에서 꺼야함.

  jwt:
    secretKey: inugraduationproject
    refreshSecretKey: jaekwonhihi

cloud:
  aws:
    credentials:
      accessKey: AKIATKJTDZVJACBPDAHB
      secretKey: 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
    s3:
      bucket: appcenter-study-bucket
      thumbnailBucket: appcenter-study-bucket-thumbnail
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


